name: Incoming PR
run-name: PR opened by ${{ github.actor }}
on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches: [main]

permissions:
  contents: read
  id-token: write

jobs:
  run-snowflake-test-dbt-job:
    name: "Run on Incoming PR"
    runs-on: ubuntu-latest
    environment: prod # Musí přesně sedět s environmentem v SUBJECT tvého OIDC usera
    env:
      SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
      SNOWFLAKE_DATABASE: ${{ vars.SNOWFLAKE_DATABASE }}
      SNOWFLAKE_SCHEMA: ${{ vars.SNOWFLAKE_SCHEMA }}

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Install Snowflake CLI
        uses: snowflakedb/snowflake-actions@v3
        with:
          use-oidc: true

      - name: Check Snowflake CLI Version
        run: snow --version

      - run: snow connection test -x

      - name: Create a new tester dbt project object in ${{ vars.SNOWFLAKE_DATABASE }}.${{ vars.SNOWFLAKE_SCHEMA }}
        run: snow dbt deploy tester_tasty_bytes_dbt_project_object_gh_action --source ./tasty_bytes_dbt_dem --dbt-version 1.11.11 -x

      - name: List all of the snowflake dbt project objects in your account
        run: snow dbt list -x

      - name: Build and test dbt project in ${{ vars.SNOWFLAKE_DATABASE }}.${{ vars.SNOWFLAKE_SCHEMA }}
        run: snow dbt execute -x tester_tasty_bytes_dbt_project_object_gh_action build --target dev
